// <auto-generated />
using System;
using System.Collections.Generic;
using Jornada.Persistencia.Postgres;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Jornada.Persistencia.Postgres.Migracoes
{
    [DbContext(typeof(ContextoDeDados))]
    [Migration("20260923110354_AjustarChaveDeEvidencia")]
    partial class AjustarChaveDeEvidencia
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("catalogo")
                .HasAnnotation("ProductVersion", "10.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Jornada.Aplicacao.Portas.ValidacaoEmProcesso", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("Ativo")
                        .HasColumnType("uuid")
                        .HasColumnName("id_item");

                    b.Property<Guid>("Empresa")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<string>("Etapa")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("etapa");

                    b.Property<Guid?>("IdDecisor")
                        .HasColumnType("uuid")
                        .HasColumnName("id_decisor");

                    b.Property<Guid>("IdSubmissor")
                        .HasColumnType("uuid")
                        .HasColumnName("id_submissor");

                    b.Property<string>("Motivo")
                        .HasColumnType("text")
                        .HasColumnName("motivo");

                    b.Property<int>("Revisao")
                        .HasColumnType("integer")
                        .HasColumnName("revisao");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status");

                    b.HasKey("Id");

                    b.HasIndex("Empresa", "Ativo")
                        .HasDatabaseName("ix_validacao_tenant_ativo");

                    b.HasIndex("Empresa", "Status")
                        .HasDatabaseName("ix_validacao_tenant_status");

                    b.ToTable("validacao", "governanca");
                });

            modelBuilder.Entity("Jornada.Dominio.Catalogo.Ativo", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("codigo_publico");

                    b.Property<DateTimeOffset>("AtualizadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("atualizado_em");

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasMaxLength(24)
                        .HasColumnType("character varying(24)")
                        .HasColumnName("codigo");

                    b.Property<DateTimeOffset>("CriadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("criado_em");

                    b.Property<string>("Criticidade")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("criticidade");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValue("")
                        .HasColumnName("descricao");

                    b.Property<Guid>("Empresa")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<DateOnly?>("FimVigencia")
                        .HasColumnType("date")
                        .HasColumnName("fim_vigencia");

                    b.Property<Guid?>("IdPai")
                        .HasColumnType("uuid")
                        .HasColumnName("id_pai");

                    b.Property<Guid?>("IdSquad")
                        .HasColumnType("uuid");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("nome");

                    b.Property<string>("Origem")
                        .IsRequired()
                        .HasMaxLength(12)
                        .HasColumnType("character varying(12)")
                        .HasColumnName("origem");

                    b.Property<int>("RevisaoAtual")
                        .HasColumnType("integer")
                        .HasColumnName("revisao_atual");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status_ciclo_vida");

                    b.Property<string>("TipoItem")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)")
                        .HasColumnName("tipo_item");

                    b.Property<Guid?>("Unidade")
                        .HasColumnType("uuid")
                        .HasColumnName("unidade_id");

                    b.Property<Dictionary<string, string>>("_atributos")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("atributos");

                    b.HasKey("Id");

                    b.HasIndex("Empresa", "Codigo")
                        .IsUnique()
                        .HasDatabaseName("ux_item_codigo");

                    b.HasIndex("Empresa", "IdPai")
                        .HasDatabaseName("ix_item_tenant_pai");

                    b.HasIndex("Empresa", "Status")
                        .HasDatabaseName("ix_item_tenant_status");

                    b.HasIndex("Empresa", "TipoItem")
                        .HasDatabaseName("ix_item_tenant_tipo");

                    b.ToTable("item_catalogo", "catalogo");
                });

            modelBuilder.Entity("Jornada.Persistencia.Postgres.MensagemDeSaida", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("ChaveDeIdempotencia")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("chave_idempotencia");

                    b.Property<Guid>("Correlacao")
                        .HasColumnType("uuid")
                        .HasColumnName("correlacao");

                    b.Property<DateTimeOffset?>("DespachadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("despachado_em");

                    b.Property<DateTimeOffset>("OcorridoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("ocorrido_em");

                    b.Property<string>("Payload")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("payload");

                    b.Property<DateTimeOffset?>("ProximaTentativa")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("proxima_tentativa");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<int>("Tentativas")
                        .HasColumnType("integer")
                        .HasColumnName("tentativas");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("tipo");

                    b.Property<string>("UltimoErro")
                        .HasColumnType("text")
                        .HasColumnName("ultimo_erro");

                    b.HasKey("Id");

                    b.ToTable("mensagem_de_saida", "catalogo", t =>
                        {
                            t.ExcludeFromMigrations();
                        });
                });

            modelBuilder.Entity("Jornada.Persistencia.Postgres.RelacaoAtivo", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTimeOffset>("CriadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("criado_em");

                    b.Property<Guid>("DestinoId")
                        .HasColumnType("uuid")
                        .HasColumnName("destino_id");

                    b.Property<Guid>("OrigemId")
                        .HasColumnType("uuid")
                        .HasColumnName("origem_id");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("tipo");

                    b.HasKey("Id");

                    b.HasIndex("TenantId", "DestinoId")
                        .HasDatabaseName("ix_relacao_tenant_destino");

                    b.HasIndex("TenantId", "OrigemId")
                        .HasDatabaseName("ix_relacao_tenant_origem");

                    b.ToTable("relacao_ativo", "catalogo");
                });

            modelBuilder.Entity("Jornada.Persistencia.Postgres.SequencialPorTipo", b =>
                {
                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<string>("TipoItem")
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)")
                        .HasColumnName("tipo_item");

                    b.Property<int>("Valor")
                        .HasColumnType("integer")
                        .HasColumnName("valor");

                    b.HasKey("TenantId", "TipoItem");

                    b.ToTable("sequencial_por_tipo", "catalogo");
                });

            modelBuilder.Entity("Jornada.Dominio.Catalogo.Ativo", b =>
                {
                    b.OwnsMany("Jornada.Dominio.Catalogo.Evidencia", "_evidencias", b1 =>
                        {
                            b1.Property<Guid>("id_item")
                                .HasColumnType("uuid");

                            b1.Property<Guid>("Id")
                                .HasColumnType("uuid");

                            b1.Property<string>("Tipo")
                                .IsRequired()
                                .HasMaxLength(30)
                                .HasColumnType("character varying(30)")
                                .HasColumnName("tipo");

                            b1.Property<string>("Titulo")
                                .IsRequired()
                                .HasMaxLength(200)
                                .HasColumnType("character varying(200)")
                                .HasColumnName("titulo");

                            b1.Property<string>("Url")
                                .HasColumnType("text")
                                .HasColumnName("url");

                            b1.HasKey("id_item", "Id");

                            b1.ToTable("evidencia", "catalogo");

                            b1.WithOwner()
                                .HasForeignKey("id_item");
                        });

                    b.OwnsMany("Jornada.Dominio.Catalogo.Responsabilidade", "_responsaveis", b1 =>
                        {
                            b1.Property<Guid>("id_item")
                                .HasColumnType("uuid");

                            b1.Property<int>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("integer");

                            NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b1.Property<int>("Id"));

                            b1.Property<DateOnly?>("FimVigencia")
                                .HasColumnType("date")
                                .HasColumnName("fim_vigencia");

                            b1.Property<Guid>("IdPessoa")
                                .HasColumnType("uuid")
                                .HasColumnName("id_pessoa");

                            b1.Property<DateOnly>("InicioVigencia")
                                .HasColumnType("date")
                                .HasColumnName("inicio_vigencia");

                            b1.Property<string>("Papel")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("papel");

                            b1.HasKey("id_item", "Id");

                            b1.ToTable("responsabilidade", "catalogo");

                            b1.WithOwner()
                                .HasForeignKey("id_item");
                        });

                    b.Navigation("_evidencias");

                    b.Navigation("_responsaveis");
                });
#pragma warning restore 612, 618
        }
    }
}
